%IBL_WITHIN_SESSION_VALIDATION_DEMO Candidate selection and within-session subset stitching validation.
%
% Run this after area PCA and PCA-QC have been computed:
%   scan = ibl_scan_sessions(cfg);
%   areaPca = ibl_compute_area_pca(scan, cfg);
%   qc = ibl_build_pca_qc_graph(cfg, scan);

setup;

cacheRoot = '/Volumes/Extreme SSD/data/neuropixel/ONE/openalyx.internationalbrainlab.org';
outputRoot = fullfile(pwd, 'ibl_output');
cfg = ibl_default_config(cacheRoot, outputRoot);
cfg.verbose = true;

tmp = load(cfg.pca_qc_file, 'qc');
qc = tmp.qc;

% First screen for sessions that are long enough and have many QC-passed areas.
candidates = ibl_find_within_session_validation_candidates(qc, cfg, ...
    'MinDuration', 600, ...
    'MinAreas', 8, ...
    'MaxAreas', 12, ...
    'TopN', 20);

disp(candidates(:, {'session_id', 'lab', 'subject', 'duration_s', ...
    'n_pass_areas', 'n_selected_areas', 'mean_pc1'}));

% Start with one or two sessions. ComputePDC=false is faster and tests CSD
% reconstruction first; set true after the CSD sanity check looks reasonable.
sessionIds = candidates.session_id(1:min(2, height(candidates)));

val = ibl_validate_within_session_subset_stitching(qc, cfg, ...
    'SessionIds', sessionIds, ...
    'MinDuration', 600, ...
    'MinAreas', 8, ...
    'MaxAreas', 12, ...
    'NumObservations', 2, ...
    'OverlapFraction', 0.35, ...
    'ComputePDC', false, ...
    'MakeFigure', true, ...
    'OutputFile', fullfile(cfg.output_root, 'validation', 'within_session_subset_stitching_top2.mat'));

disp(struct2table(arrayfun(@(r) r.metrics, val.records)));
